### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'source_address'

### ISSUE THREAD

**Issue by gmourani** [jonwitts/nagios-speedtest#6]
Hello,

Running speedtest --simple return the following:

Traceback (most recent call last):
  File "/usr/bin/speedtest", line 1843, in <module>
    main()
  File "/usr/bin/speedtest", line 1832, in main
    shell()
  File "/usr/bin/speedtest", line 1729, in shell
    secure=args.secure
  File "/usr/bin/speedtest", line 1009, in __init__
    self.get_config()
  File "/usr/bin/speedtest", line 1042, in get_config
    uh, e = catch_request(request, opener=self._opener)
  File "/usr/bin/speedtest", line 650, in catch_request
    uh = _open(request)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 616, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/bin/speedtest", line 489, in https_open
    req
  File "/usr/lib64/python2.6/urllib2.py", line 1136, in do_open
    h = http_class(host, timeout=req.timeout) # will parse host:port
  File "/usr/bin/speedtest", line 444, in inner
    return connection(host, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source_address'

It was working in the past!

Regards,

**Comment by jonwitts** [comment]
This looks like an error with the speedtest binary... Have you tried updating it or reporting this over on their GitHub page? https://github.com/sivel/speedtest-cli 

I don't think this is an error with my script...

**Comment by gmourani** [comment]
Hello,

Yes you're right, it's not from your script but from the binary, thanks for your reply.
